# Generated by Django 5.1.3 on 2024-12-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mermaiddiagram',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
